name: Auto Run Stock System

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1-5"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:

      # =========================
      # Checkout
      # =========================
      - name: Checkout repository
        uses: actions/checkout@v4

      # =========================
      # Python
      # =========================
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # =========================
      # Install
      # =========================
      - name: Install dependencies
        run: |
          pip install pandas requests openpyxl pytz

      # =========================
      # Pull latest
      # 必須放在 main.py 前面
      # =========================
      - name: Pull latest changes
        run: |
          git pull origin main --rebase

      # =========================
      # Run
      # =========================
      - name: Run main.py
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: |
          python main.py

      # =========================
      # Commit
      # =========================
      - name: Commit files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add .

          git commit -m "auto update stock data" || echo "No changes"

          git push origin main
